services:
  db:
    image: 'postgres:14'
    container_name: db
    networks:
      - application-net
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'db_cooperfilme'
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    image: api-cooperfilme
    container_name: api_cooperfilme
    networks:
      - application-net
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  appCliente:
    image: app-cliente
    container_name: app_cliente
    networks:
      - application-net
    restart: always
    build: 
      context: ./app-cliente
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
  appUsuario:
    image: app-usuario
    container_name: app_usuario
    networks:
      - application-net
    restart: always
    build: 
      context: ./app-usuario
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - api
volumes: 
  db-data:
networks:
  application-net:
    driver: bridge